// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: api/v1/error/error.proto

package error

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReson int32

const (
	ErrorReson_ARTICLE_NOT_FOUND ErrorReson = 0
)

// Enum value maps for ErrorReson.
var (
	ErrorReson_name = map[int32]string{
		0: "ARTICLE_NOT_FOUND",
	}
	ErrorReson_value = map[string]int32{
		"ARTICLE_NOT_FOUND": 0,
	}
)

func (x ErrorReson) Enum() *ErrorReson {
	p := new(ErrorReson)
	*p = x
	return p
}

func (x ErrorReson) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReson) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_error_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReson) Type() protoreflect.EnumType {
	return &file_api_v1_error_error_proto_enumTypes[0]
}

func (x ErrorReson) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReson.Descriptor instead.
func (ErrorReson) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_error_error_proto_rawDescGZIP(), []int{0}
}

var File_api_v1_error_error_proto protoreflect.FileDescriptor

const file_api_v1_error_error_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1/error/error.proto\x12\fapi.v1.error\x1a\x13errors/errors.proto*/\n" +
	"\n" +
	"ErrorReson\x12\x1b\n" +
	"\x11ARTICLE_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x1a\x04\xa0E\xf4\x03B\x1bZ\x19myblog/api/v1/error;errorb\x06proto3"

var (
	file_api_v1_error_error_proto_rawDescOnce sync.Once
	file_api_v1_error_error_proto_rawDescData []byte
)

func file_api_v1_error_error_proto_rawDescGZIP() []byte {
	file_api_v1_error_error_proto_rawDescOnce.Do(func() {
		file_api_v1_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_error_error_proto_rawDesc), len(file_api_v1_error_error_proto_rawDesc)))
	})
	return file_api_v1_error_error_proto_rawDescData
}

var file_api_v1_error_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_error_error_proto_goTypes = []any{
	(ErrorReson)(0), // 0: api.v1.error.ErrorReson
}
var file_api_v1_error_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_error_error_proto_init() }
func file_api_v1_error_error_proto_init() {
	if File_api_v1_error_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_error_error_proto_rawDesc), len(file_api_v1_error_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_error_error_proto_goTypes,
		DependencyIndexes: file_api_v1_error_error_proto_depIdxs,
		EnumInfos:         file_api_v1_error_error_proto_enumTypes,
	}.Build()
	File_api_v1_error_error_proto = out.File
	file_api_v1_error_error_proto_goTypes = nil
	file_api_v1_error_error_proto_depIdxs = nil
}
