// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"myblog/internal/biz"
	"myblog/internal/conf"
	"myblog/internal/data"
	"myblog/internal/server"
	"myblog/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUseCase := biz.NewArticleUseCase(articleRepo)
	articleService := service.NewArticleService(articleUseCase, logger)
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUseCase := biz.NewCommentUseCase(commentRepo)
	commentService := service.NewCommentService(commentUseCase, logger)
	tagRepo := data.NewTagRepo(dataData)
	tagUseCase := biz.NewTagUseCase(tagRepo)
	tagService := service.NewTagService(tagUseCase, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := service.NewUserService(userUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, articleService, commentService, tagService, userService, logger)
	httpServer := server.NewHTTPServer(confServer, articleService, commentService, tagService, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
