// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: api/v1/tag/tag.proto

package tag

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagReply) Reset() {
	*x = CreateTagReply{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagReply) ProtoMessage() {}

func (x *CreateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagReply.ProtoReflect.Descriptor instead.
func (*CreateTagReply) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{2}
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagReply) Reset() {
	*x = UpdateTagReply{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagReply) ProtoMessage() {}

func (x *UpdateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagReply.ProtoReflect.Descriptor instead.
func (*UpdateTagReply) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{4}
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagReply) Reset() {
	*x = DeleteTagReply{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagReply) ProtoMessage() {}

func (x *DeleteTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagReply.ProtoReflect.Descriptor instead.
func (*DeleteTagReply) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{6}
}

type GetTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       string                 `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{7}
}

func (x *GetTagRequest) GetArticle() string {
	if x != nil {
		return x.Article
	}
	return ""
}

type GetTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagReply) Reset() {
	*x = GetTagReply{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagReply) ProtoMessage() {}

func (x *GetTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagReply.ProtoReflect.Descriptor instead.
func (*GetTagReply) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{8}
}

func (x *GetTagReply) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagRequest) Reset() {
	*x = ListTagRequest{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRequest) ProtoMessage() {}

func (x *ListTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRequest.ProtoReflect.Descriptor instead.
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{9}
}

type ListTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagReply) Reset() {
	*x = ListTagReply{}
	mi := &file_api_v1_tag_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagReply) ProtoMessage() {}

func (x *ListTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tag_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagReply.ProtoReflect.Descriptor instead.
func (*ListTagReply) Descriptor() ([]byte, []int) {
	return file_api_v1_tag_tag_proto_rawDescGZIP(), []int{10}
}

func (x *ListTagReply) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_api_v1_tag_tag_proto protoreflect.FileDescriptor

const file_api_v1_tag_tag_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/tag/tag.proto\x12\n" +
	"api.v1.tag\x1a\x1cgoogle/api/annotations.proto\")\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"&\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x10\n" +
	"\x0eCreateTagReply\"6\n" +
	"\x10UpdateTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x10\n" +
	"\x0eUpdateTagReply\"\"\n" +
	"\x10DeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteTagReply\")\n" +
	"\rGetTagRequest\x12\x18\n" +
	"\aarticle\x18\x01 \x01(\tR\aarticle\"2\n" +
	"\vGetTagReply\x12#\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.api.v1.tag.TagR\x04tags\"\x10\n" +
	"\x0eListTagRequest\"3\n" +
	"\fListTagReply\x12#\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.api.v1.tag.TagR\x04tags2\xd5\x03\n" +
	"\n" +
	"TagService\x12Z\n" +
	"\tCreateTag\x12\x1c.api.v1.tag.CreateTagRequest\x1a\x1a.api.v1.tag.CreateTagReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/api/tag\x12_\n" +
	"\tUpdateTag\x12\x1c.api.v1.tag.UpdateTagRequest\x1a\x1a.api.v1.tag.UpdateTagReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/api/tag/{id}\x12\\\n" +
	"\tDeleteTag\x12\x1c.api.v1.tag.DeleteTagRequest\x1a\x1a.api.v1.tag.DeleteTagReply\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/api/tag/{id}\x12X\n" +
	"\x06GetTag\x12\x19.api.v1.tag.GetTagRequest\x1a\x17.api.v1.tag.GetTagReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/tag/{article}\x12R\n" +
	"\aListTag\x12\x1a.api.v1.tag.ListTagRequest\x1a\x18.api.v1.tag.ListTagReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/tagsB\x17Z\x15myblog/api/v1/tag;tagb\x06proto3"

var (
	file_api_v1_tag_tag_proto_rawDescOnce sync.Once
	file_api_v1_tag_tag_proto_rawDescData []byte
)

func file_api_v1_tag_tag_proto_rawDescGZIP() []byte {
	file_api_v1_tag_tag_proto_rawDescOnce.Do(func() {
		file_api_v1_tag_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_tag_tag_proto_rawDesc), len(file_api_v1_tag_tag_proto_rawDesc)))
	})
	return file_api_v1_tag_tag_proto_rawDescData
}

var file_api_v1_tag_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_tag_tag_proto_goTypes = []any{
	(*Tag)(nil),              // 0: api.v1.tag.Tag
	(*CreateTagRequest)(nil), // 1: api.v1.tag.CreateTagRequest
	(*CreateTagReply)(nil),   // 2: api.v1.tag.CreateTagReply
	(*UpdateTagRequest)(nil), // 3: api.v1.tag.UpdateTagRequest
	(*UpdateTagReply)(nil),   // 4: api.v1.tag.UpdateTagReply
	(*DeleteTagRequest)(nil), // 5: api.v1.tag.DeleteTagRequest
	(*DeleteTagReply)(nil),   // 6: api.v1.tag.DeleteTagReply
	(*GetTagRequest)(nil),    // 7: api.v1.tag.GetTagRequest
	(*GetTagReply)(nil),      // 8: api.v1.tag.GetTagReply
	(*ListTagRequest)(nil),   // 9: api.v1.tag.ListTagRequest
	(*ListTagReply)(nil),     // 10: api.v1.tag.ListTagReply
}
var file_api_v1_tag_tag_proto_depIdxs = []int32{
	0,  // 0: api.v1.tag.GetTagReply.tags:type_name -> api.v1.tag.Tag
	0,  // 1: api.v1.tag.ListTagReply.tags:type_name -> api.v1.tag.Tag
	1,  // 2: api.v1.tag.TagService.CreateTag:input_type -> api.v1.tag.CreateTagRequest
	3,  // 3: api.v1.tag.TagService.UpdateTag:input_type -> api.v1.tag.UpdateTagRequest
	5,  // 4: api.v1.tag.TagService.DeleteTag:input_type -> api.v1.tag.DeleteTagRequest
	7,  // 5: api.v1.tag.TagService.GetTag:input_type -> api.v1.tag.GetTagRequest
	9,  // 6: api.v1.tag.TagService.ListTag:input_type -> api.v1.tag.ListTagRequest
	2,  // 7: api.v1.tag.TagService.CreateTag:output_type -> api.v1.tag.CreateTagReply
	4,  // 8: api.v1.tag.TagService.UpdateTag:output_type -> api.v1.tag.UpdateTagReply
	6,  // 9: api.v1.tag.TagService.DeleteTag:output_type -> api.v1.tag.DeleteTagReply
	8,  // 10: api.v1.tag.TagService.GetTag:output_type -> api.v1.tag.GetTagReply
	10, // 11: api.v1.tag.TagService.ListTag:output_type -> api.v1.tag.ListTagReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_tag_tag_proto_init() }
func file_api_v1_tag_tag_proto_init() {
	if File_api_v1_tag_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_tag_tag_proto_rawDesc), len(file_api_v1_tag_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_tag_tag_proto_goTypes,
		DependencyIndexes: file_api_v1_tag_tag_proto_depIdxs,
		MessageInfos:      file_api_v1_tag_tag_proto_msgTypes,
	}.Build()
	File_api_v1_tag_tag_proto = out.File
	file_api_v1_tag_tag_proto_goTypes = nil
	file_api_v1_tag_tag_proto_depIdxs = nil
}
