// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: api/v1/article/article.proto

package article

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_api_v1_article_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_api_v1_article_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReply) Reset() {
	*x = CreateArticleReply{}
	mi := &file_api_v1_article_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReply) ProtoMessage() {}

func (x *CreateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReply.ProtoReflect.Descriptor instead.
func (*CreateArticleReply) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleReply) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_api_v1_article_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReply) Reset() {
	*x = UpdateArticleReply{}
	mi := &file_api_v1_article_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReply) ProtoMessage() {}

func (x *UpdateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReply.ProtoReflect.Descriptor instead.
func (*UpdateArticleReply) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateArticleReply) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_api_v1_article_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReply) Reset() {
	*x = DeleteArticleReply{}
	mi := &file_api_v1_article_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReply) ProtoMessage() {}

func (x *DeleteArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReply.ProtoReflect.Descriptor instead.
func (*DeleteArticleReply) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{6}
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_api_v1_article_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReply) Reset() {
	*x = GetArticleReply{}
	mi := &file_api_v1_article_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReply) ProtoMessage() {}

func (x *GetArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReply.ProtoReflect.Descriptor instead.
func (*GetArticleReply) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleReply) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleRequest) Reset() {
	*x = ListArticleRequest{}
	mi := &file_api_v1_article_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleRequest) ProtoMessage() {}

func (x *ListArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleRequest.ProtoReflect.Descriptor instead.
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{9}
}

type ListArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleReply) Reset() {
	*x = ListArticleReply{}
	mi := &file_api_v1_article_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleReply) ProtoMessage() {}

func (x *ListArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_article_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleReply.ProtoReflect.Descriptor instead.
func (*ListArticleReply) Descriptor() ([]byte, []int) {
	return file_api_v1_article_article_proto_rawDescGZIP(), []int{10}
}

func (x *ListArticleReply) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

var File_api_v1_article_article_proto protoreflect.FileDescriptor

const file_api_v1_article_article_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1/article/article.proto\x12\x0eapi.v1.article\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"F\n" +
	"\x14CreateArticleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"G\n" +
	"\x12CreateArticleReply\x121\n" +
	"\aarticle\x18\x01 \x01(\v2\x17.api.v1.article.ArticleR\aarticle\"V\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"G\n" +
	"\x12UpdateArticleReply\x121\n" +
	"\aarticle\x18\x01 \x01(\v2\x17.api.v1.article.ArticleR\aarticle\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteArticleReply\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x0fGetArticleReply\x121\n" +
	"\aarticle\x18\x01 \x01(\v2\x17.api.v1.article.ArticleR\aarticle\"\x14\n" +
	"\x12ListArticleRequest\"G\n" +
	"\x10ListArticleReply\x123\n" +
	"\barticles\x18\x01 \x03(\v2\x17.api.v1.article.ArticleR\barticles2\xcc\x04\n" +
	"\x0eArticleService\x12r\n" +
	"\rCreateArticle\x12$.api.v1.article.CreateArticleRequest\x1a\".api.v1.article.CreateArticleReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/article\x12w\n" +
	"\rUpdateArticle\x12$.api.v1.article.UpdateArticleRequest\x1a\".api.v1.article.UpdateArticleReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/article/{id}\x12t\n" +
	"\rDeleteArticle\x12$.api.v1.article.DeleteArticleRequest\x1a\".api.v1.article.DeleteArticleReply\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/article/{id}\x12k\n" +
	"\n" +
	"GetArticle\x12!.api.v1.article.GetArticleRequest\x1a\x1f.api.v1.article.GetArticleReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/article/{id}\x12j\n" +
	"\vListArticle\x12\".api.v1.article.ListArticleRequest\x1a .api.v1.article.ListArticleReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/articlesB\x1fZ\x1dmyblog/api/v1/article;articleb\x06proto3"

var (
	file_api_v1_article_article_proto_rawDescOnce sync.Once
	file_api_v1_article_article_proto_rawDescData []byte
)

func file_api_v1_article_article_proto_rawDescGZIP() []byte {
	file_api_v1_article_article_proto_rawDescOnce.Do(func() {
		file_api_v1_article_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_article_article_proto_rawDesc), len(file_api_v1_article_article_proto_rawDesc)))
	})
	return file_api_v1_article_article_proto_rawDescData
}

var file_api_v1_article_article_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_article_article_proto_goTypes = []any{
	(*Article)(nil),              // 0: api.v1.article.Article
	(*CreateArticleRequest)(nil), // 1: api.v1.article.CreateArticleRequest
	(*CreateArticleReply)(nil),   // 2: api.v1.article.CreateArticleReply
	(*UpdateArticleRequest)(nil), // 3: api.v1.article.UpdateArticleRequest
	(*UpdateArticleReply)(nil),   // 4: api.v1.article.UpdateArticleReply
	(*DeleteArticleRequest)(nil), // 5: api.v1.article.DeleteArticleRequest
	(*DeleteArticleReply)(nil),   // 6: api.v1.article.DeleteArticleReply
	(*GetArticleRequest)(nil),    // 7: api.v1.article.GetArticleRequest
	(*GetArticleReply)(nil),      // 8: api.v1.article.GetArticleReply
	(*ListArticleRequest)(nil),   // 9: api.v1.article.ListArticleRequest
	(*ListArticleReply)(nil),     // 10: api.v1.article.ListArticleReply
}
var file_api_v1_article_article_proto_depIdxs = []int32{
	0,  // 0: api.v1.article.CreateArticleReply.article:type_name -> api.v1.article.Article
	0,  // 1: api.v1.article.UpdateArticleReply.article:type_name -> api.v1.article.Article
	0,  // 2: api.v1.article.GetArticleReply.article:type_name -> api.v1.article.Article
	0,  // 3: api.v1.article.ListArticleReply.articles:type_name -> api.v1.article.Article
	1,  // 4: api.v1.article.ArticleService.CreateArticle:input_type -> api.v1.article.CreateArticleRequest
	3,  // 5: api.v1.article.ArticleService.UpdateArticle:input_type -> api.v1.article.UpdateArticleRequest
	5,  // 6: api.v1.article.ArticleService.DeleteArticle:input_type -> api.v1.article.DeleteArticleRequest
	7,  // 7: api.v1.article.ArticleService.GetArticle:input_type -> api.v1.article.GetArticleRequest
	9,  // 8: api.v1.article.ArticleService.ListArticle:input_type -> api.v1.article.ListArticleRequest
	2,  // 9: api.v1.article.ArticleService.CreateArticle:output_type -> api.v1.article.CreateArticleReply
	4,  // 10: api.v1.article.ArticleService.UpdateArticle:output_type -> api.v1.article.UpdateArticleReply
	6,  // 11: api.v1.article.ArticleService.DeleteArticle:output_type -> api.v1.article.DeleteArticleReply
	8,  // 12: api.v1.article.ArticleService.GetArticle:output_type -> api.v1.article.GetArticleReply
	10, // 13: api.v1.article.ArticleService.ListArticle:output_type -> api.v1.article.ListArticleReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_article_article_proto_init() }
func file_api_v1_article_article_proto_init() {
	if File_api_v1_article_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_article_article_proto_rawDesc), len(file_api_v1_article_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_article_article_proto_goTypes,
		DependencyIndexes: file_api_v1_article_article_proto_depIdxs,
		MessageInfos:      file_api_v1_article_article_proto_msgTypes,
	}.Build()
	File_api_v1_article_article_proto = out.File
	file_api_v1_article_article_proto_goTypes = nil
	file_api_v1_article_article_proto_depIdxs = nil
}
